### ISSUE TITLE
Add options to define SMB settings

### ISSUE THREAD

**Issue by sascha-egerer** [Azure/azurefile-dockervolumedriver#18]
There should be options to define the SMB settings uid, gid, file_mode, and dir_mode.

Currently file_mode and dir_mode is hardcoded to 777 which is problematic in some cases.

**Comment by ahmetb** [comment]
@sascha-egerer could you explain the problematic cases a bit more? I'd love to understand the motive behind that. We're using 0777 just because that's what the Azure File Service documentation says.

**Comment by sascha-egerer** [comment]
`0777` means read, write and execute for everyone. I would like to mount a folder that is only readable by a specific user. So i need to set `file_mode=0700` and `uid=123`.

**Comment by ahmetb** [comment]
@sascha-egerer your request makes sense. From a security standpoint, since we mount the SMB share on the host and make it available to container, anybody on the host can read the files as they are 0777. 

We can easily add a flag for chmod of the share. However I'm not so sure about uid. Are you mapping the uid inside the container to outside the container somehow (using user namespaces maybe?). I'm trying to understand how are you going to use the same uid that we pass to the `mount` command on the host inside the container? 

What kind of flag would you like to see for uid? Should it be just a uid number or a username as well?

By the way if you want your container to have read-only access you can mount the share like `-v vol:/path:ro` in docker, that can temporarily solve your problem.

**Comment by sascha-egerer** [comment]
@ahmetalpbalkan no i don't want a read only volume. I just want that the volume is not mounted with 777 but 750 ;-)

Not sure if a username does work as uid in the mount command. But i think this uid has nothing to do with the uid of the host system. The mounted volume is just mapped to the defined uid of the container. 
At least is this what i would expect. I've not yet tested it.
So if i have a "www" user i may wan't to mount the volume with `750` and `www` as owner.

**Comment by ahmetb** [comment]
@sascha-egerer we can resolve the id for the username fairly easily. that's not a problem.

What I'm trying to understand is, is the `www` user inside the container or outside the container? If the user is present outside the container and not inside, then the mounted share will have an owner that's not in the user namespace of the container, and therefore it'll show `nobody:nogroup` instead of `www:www'sgroup`.

**Comment by sascha-egerer** [comment]
Yeah i think it does only make sense if the user is inside the container. Everything else does not make sense...
The usecase is as described above. I have 3 users in my container. One is `root` and one is `www` and one is `johndoe`. I would mount a volume that is accessable by `www` but not by `johndoe`.
So I have to mount the volume with `0700` and the `uid` of `www`.

**Comment by ahmetb** [comment]
@sascha-egerer just circling back on this, I believe the problem you'll see that is `www` will only be inside a container, so this volume driver (runs outside container, directly on host) pretty much won't have a way of knowing uid of `www` inside the container.

I can't think of any solutions for that except `docker run --user <uid|name>`. Perhaps if we mount the share as `www` on the host (so `www` must exist on the host) and you start the container with `docker run --user www [...]` then it could work.

I suggest you to play with this idea a bit, if you can find an ideal solution that works for you, we can implement it.

**Comment by sascha-egerer** [comment]
@ahmetalpbalkan It was not clear to me that the mount is executed on the host system. I thought it is mounted directly in the container.
So defining a gid or uid does not make sense in this case. So forget about this request.

**Comment by ahmetb** [comment]
@sascha-egerer thanks for clarifying. it probably still makes a bit of sense, if you're gonna reuse the same host-user inside the container (some people actually do that), even when you don't use `docker run --user`, I guess we can allow people to do a 0700 so that only root can see the files and not another host-user.

**Comment by ahmetb** [comment]
Closing as we do not need to implement this.
