### ISSUE TITLE
incorrect names in defaults for systemd setup

### ISSUE THREAD

**Issue by bertvannuffelen** [Azure/azurefile-dockervolumedriver#38]
Dear,
in https://github.com/Azure/azurefile-dockervolumedriver/blob/master/contrib/init/systemd/azurefile-dockervolumedriver.default the parameters are called 
AZURE_STORAGE_ACCOUNT=
AZURE_STORAGE_ACCOUNT_KEY=

while only these are being loaded
AF_ACCOUNT_NAME=
AF_ACCOUNT_KEY=

kr,

Bert

**Comment by ahmetb** [comment]
@bertvannuffelen this should not be an issue. the program actually looks for AZURE_ keys. It's just the upstart script that has the AF_ keys (and that's for the backwards compatibility reasons).

Are you seeing a different behavior?

**Comment by bertvannuffelen** [comment]
When I copied the systemd service description and the configuration file next to it to the target locations the driver did not start.
When adding the above parameters it started all fine.

(behaviour experienced on on an Ubuntu Xenial and ubuntu 15.04 )

**Comment by ahmetb** [comment]
@bertvannuffelen are you sure you don't have an instance of upstart also running on your system?

The code does not even have anything mentioning `AF_` variables:

https://github.com/Azure/azurefile-dockervolumedriver/blob/master/main.go

are you using the latest version in the Releases tab?

**Comment by bertvannuffelen** [comment]
I am building the driver from source. And then copy the service descriptions.

kr,

Bert

**Comment by ahmetb** [comment]
@bertvannuffelen I just tried it with 0.2.1 binary release (I'm confident we haven't changed the code for this) and followed instructions at https://github.com/Azure/azurefile-dockervolumedriver/blob/master/contrib/init/systemd/README.md and it worked for me on Ubuntu 16.04.

Can you please try with 16.04? The 15.04 is not supported since February 2016. https://wiki.ubuntu.com/Releases
